tap 'peco/peco'
brew 'tig'
brew 'vim', args: ['with-lua']
brew 'emacs', args: ['with-d-bus']
brew 'zsh'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'ctags'
brew 'coreutils'
brew 'the_silver_searcher'
brew 'fasd'
brew 'direnv'
brew 'ispell'
brew 'w3m'
brew 'wget'
brew 'offlineimap'
brew 'gpg'
brew 'mu'
brew 'gnutls'
brew 'hub'
brew 'fortune'
brew 'cowsay'
brew 'go'
brew 'automake'
brew 'aspell'
brew 'cheat'
brew 'python'

brew 'caskroom/cask/brew-cask'
cask 'iterm2'
cask 'firefox'
cask 'google-chrome'
cask 'dropbox'
cask 'alfred'
cask 'google-japanese-ime'
cask 'dash'
cask 'lastpass'
cask 'karabiner'
