(helm-mode 1)
(define-key helm-map (kbd "C-h") 'delete-backward-char)
(define-key helm-find-files-map (kbd "C-h") 'delete-backward-char)
(define-key helm-map (kbd "C-w") 'evil-delete-backward-word)
(define-key helm-find-files-map (kbd "C-w") 'evil-delete-backward-word)
