omap af <Plug>(textobj-function-a)
xmap af <Plug>(textobj-function-a)
omap if <Plug>(textobj-function-i)
xmap if <Plug>(textobj-function-i)
omap aF <Plug>(textobj-function-A)
xmap aF <Plug>(textobj-function-A)
omap iF <Plug>(textobj-function-I)
xmap iF <Plug>(textobj-function-I)
