#!/bin/sh

# For git pre-push hook

# See file status life cycle: http://git-scm.com/book/en/Git-Basics-Recording-Changes-to-the-Repository
untracked=$(git status --porcelain 2>/dev/null | grep "^??")
modified=$(git status --porcelain 2>/dev/null | grep "^ M")
staged=$(git status --porcelain 2>/dev/null | grep "^M")

if [ -n "$untracked" -o -n "$modified" -o -n "$staged" ]; then
  echo "Working tree not clean." 1>&2
  exit 1
fi
