# zpofile is loaded only for login shell, after zshenv (man 1 zsh)

# about EDITOR and VISUAL: https://unix.stackexchange.com/a/4861
export VISUAL="nvim"
export EDITOR="$VISUAL"
export GIT_EDITOR="$VISUAL"

# Load local zprofile
[ -f $HOME/.zprofile.local ] && source $HOME/.zprofile.local

# vim:filetype=zsh
