# Plugins {{{
eval "$(fasd --init auto)"
eval "$(direnv hook zsh)"
# }}}

rcfiles=(
  prompt.zsh
  history.zsh
  zle.zsh
  git.zsh
  nvim.zsh
)
for f in $rcfiles
do
  source $DOTDIR/zshfiles/rcfiles/$f
done

# vim:foldmethod=marker
