---
- zshfiles:
    - zshrc
    - zshenv
- vimfiles:
    - vim
    - vimrc
- rubyfiles:
    - pryrc
- gitfiles:
    - gitconfig
    - gitignore_global
    - git_template_dir
    - githooks
    - tigrc
- miscfiles:
    - ctags
    - latexmkrc
    - tmux.conf
    - vimperator
    - vimperatorrc
    - inputrc
    - editrc
    - envrc
    - offlineimaprc
    - offlineimap.py
    - js
    - cheat
- emacs.d
- clicoder.d
