---
- zshfiles:
    - zshrc
    - zshenv
- vimfiles:
    - vim
    - vimrc
    - gvimrc
- rubyfiles:
    - pryrc
- gitfiles:
    - gitconfig
    - gitignore_global
    - git_template_dir
    - githooks
    - tigrc
- miscfiles:
    - ctags
    - latexmkrc
    - tmux.conf
    - vimperator
    - vimperatorrc
    - inputrc
    - editrc
    - envrc
    - offlineimaprc
    - offlineimap.py
    - js
    - cheat
    - overcommit.yml
    - mayu
    - globalrc
    - zazurc.json
    - urlview
    - pam_environment
    - xinitrc
    - Xresources
    - Xresources.d
    - Xmodmap
- emacs.d
- clicoder.d
