---
- zshfiles:
    - zshrc
    - zshenv
- vimfiles:
    - vim
    - vimrc
    - vimrc.minimal
- rubyfiles:
    - pryrc
- gitfiles:
    - gitconfig
    - gitignore_global
    - git_hooks
- miscfiles:
    - ctags
    - latexmkrc
    - tmux.conf
    - vimperator
    - vimperatorrc
    - inputrc
    - editrc
    - envrc
    - offlineimaprc
    - offlineimap.py
    - js
- emacs.d
- percol.d
