[cursor]
# Values for `style`:
#   - ▇ Block
#   - _ Underline
#   - | Beam
style = "Block"
# If this is `true`, the cursor will be rendered as a hollow box when the
# window is not focused.
unfocused_hollow = true

[font]
size = 24.0

[font.bold]
family = "Cica"
style = "Bold"

[font.bold_italic]
family = "Cica"
style = "Bold Italic"

[font.italic]
family = "Cica"
style = "Italic"

[font.normal]
family = "Cica"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Alt"
