#!/bin/sh

# https://wiki.archlinux.org/index.php/Xinit
# https://wiki.archlinux.org/index.php/i3

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
  xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
  xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
  xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

fcitx &
unclutter &
picom &
[ -f ~/.fehbg ] && ~/.fehbg &
redshift -l 35.6852:139.7528 &

[ -f ~/.xinitrc.local ] && source ~/.xinitrc.local

exec i3
